version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pass@word1
    ports: 
      - 1433:1433
    volumes:
      - /c/work/FH.../mssqldata:/var/opt/mssql/data/
  adminer:
    image: knom/adminer-mssql
    ports:
      - 8080:8080
    environment:
       - ADMINER_PLUGINS=tinymce
       - ADMINER_DESIGN=flat
       - ADMINER_DEFAULT_SERVER=sqlserver